/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuiLoading: typeof import('./src/components/aui-loading/aui-loading.vue')['default']
    AuthorF: typeof import('./src/components/common/AuthorF.vue')['default']
    CheckBox: typeof import('./src/components/common/CheckBox.vue')['default']
    CitySelect: typeof import('./src/components/city-select/city-select.vue')['default']
    CommonImage: typeof import('./src/components/common/CommonImage.vue')['default']
    FavorBtn: typeof import('./src/components/common/FavorBtn.vue')['default']
    FollowBtn: typeof import('./src/components/common/FollowBtn.vue')['default']
    FontIcon: typeof import('./src/components/common/FontIcon.vue')['default']
    MoreContent: typeof import('./src/components/common/MoreContent.vue')['default']
    NewsListItem: typeof import('./src/components/common/NewsListItem.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutDivider: typeof import('nutui-uniapp/components/divider/divider.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutSearchbar: typeof import('nutui-uniapp/components/searchbar/searchbar.vue')['default']
    NutSignature: typeof import('nutui-uniapp/components/signature/signature.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    PostForm: typeof import('./src/components/common/PostForm.vue')['default']
    PostListItem: typeof import('./src/components/common/PostListItem.vue')['default']
    PullList: typeof import('./src/components/common/PullList.vue')['default']
    RadarCharts: typeof import('./src/components/common/RadarCharts.vue')['default']
    ScrollList: typeof import('./src/components/common/ScrollList.vue')['default']
    Share: typeof import('./src/components/share/index.vue')['default']
    WxKefu: typeof import('./src/components/common/WxKefu.vue')['default']
  }
}
