/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuiLoading: typeof import('./components/aui-loading/aui-loading.vue')['default']
    AuthorF: typeof import('./components/common/AuthorF.vue')['default']
    CheckBox: typeof import('./components/common/CheckBox.vue')['default']
    CitySelect: typeof import('./components/city-select/city-select.vue')['default']
    CommonImage: typeof import('./components/common/CommonImage.vue')['default']
    FavorBtn: typeof import('./components/common/FavorBtn.vue')['default']
    FollowBtn: typeof import('./components/common/FollowBtn.vue')['default']
    MoreContent: typeof import('./components/common/MoreContent.vue')['default']
    NewsListItem: typeof import('./components/common/NewsListItem.vue')['default']
    PostForm: typeof import('./components/common/PostForm.vue')['default']
    PostListItem: typeof import('./components/common/PostListItem.vue')['default']
    PullList: typeof import('./components/common/PullList.vue')['default']
    RadarCharts: typeof import('./components/common/RadarCharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollList: typeof import('./components/common/ScrollList.vue')['default']
    UIcon: typeof import('./components/common/UIcon.vue')['default']
    WxKefu: typeof import('./components/common/WxKefu.vue')['default']
  }
}
